/**
 * Client-side behaviors. Pages are static HTML generated by
 * scripts/build-content.mjs; this file only adds progressive enhancement:
 * sticky header, fullscreen menu, listing filters/sort, detail tabs, lightbox.
 */
import '@fontsource/jost/200.css';
import '@fontsource/jost/300.css';
import '@fontsource/barlow/400.css';
import '@fontsource/barlow/500.css';
import '@fontsource/barlow/600.css';
import '@fontsource/barlow/700.css';
import '@fontsource/cormorant/500-italic.css';
import './styles/main.css';

// ---- sticky header ----
function onScroll(): void {
  document.body.classList.toggle('is-scrolled', window.scrollY > 40);
}
window.addEventListener('scroll', onScroll, { passive: true });
onScroll();

// ---- fullscreen menu ----
const menu = document.querySelector<HTMLElement>('[data-menu]');
if (menu) {
  menu.hidden = true;
  document.querySelector('[data-menu-open]')?.addEventListener('click', () => (menu.hidden = false));
  menu.querySelector('[data-menu-close]')?.addEventListener('click', () => (menu.hidden = true));
  menu.querySelectorAll('a').forEach((a) => a.addEventListener('click', () => (menu.hidden = true)));
  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') menu.hidden = true;
  });
}

// ---- listings index: filter + sort ----
const grid = document.querySelector<HTMLElement>('[data-listing-grid]');
if (grid) {
  const hoodSelect = document.querySelector<HTMLSelectElement>('[data-filter-hood]');
  const sortSelect = document.querySelector<HTMLSelectElement>('[data-sort]');
  const emptyNote = document.querySelector<HTMLElement>('[data-empty-note]');
  const cards = Array.from(grid.querySelectorAll<HTMLElement>('.property-card'));

  const apply = (): void => {
    const hood = hoodSelect?.value ?? '';
    const sort = sortSelect?.value ?? 'recent';

    const sorted = [...cards].sort((a, b) => {
      const pa = Number(a.dataset.price);
      const pb = Number(b.dataset.price);
      if (sort === 'price-asc') return pa - pb;
      if (sort === 'price-desc') return pb - pa;
      return (b.dataset.date ?? '').localeCompare(a.dataset.date ?? '');
    });

    let visible = 0;
    for (const card of sorted) {
      const show = !hood || card.dataset.hood === hood;
      card.style.display = show ? '' : 'none';
      if (show) visible++;
      grid.appendChild(card);
    }
    if (emptyNote) emptyNote.hidden = visible > 0;
  };

  hoodSelect?.addEventListener('change', apply);
  sortSelect?.addEventListener('change', apply);
  apply();
}

// ---- detail page: tabs ----
const tabs = document.querySelector<HTMLElement>('[data-tabs]');
if (tabs) {
  tabs.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach((btn) => {
    btn.addEventListener('click', () => {
      tabs.querySelectorAll('[data-tab]').forEach((b) => b.classList.toggle('is-active', b === btn));
      tabs
        .querySelectorAll<HTMLElement>('[data-panel]')
        .forEach((p) => p.classList.toggle('is-active', p.dataset.panel === btn.dataset.tab));
    });
  });
}

// ---- detail page: gallery lightbox ----
const gallery = document.querySelector<HTMLElement>('[data-gallery]');
const lightbox = document.querySelector<HTMLElement>('[data-lightbox]');
if (gallery && lightbox) {
  const photos = Array.from(gallery.querySelectorAll<HTMLTemplateElement>('[data-full-photo]')).map(
    (t) => t.content.textContent?.trim() ?? '',
  );
  const img = lightbox.querySelector<HTMLImageElement>('[data-lightbox-img]');
  const counter = lightbox.querySelector<HTMLElement>('[data-lightbox-counter]');
  let index = 0;

  const show = (i: number): void => {
    index = (i + photos.length) % photos.length;
    if (img) img.src = photos[index];
    if (counter) counter.textContent = `${index + 1} / ${photos.length}`;
    lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
  };
  const close = (): void => {
    lightbox.hidden = true;
    document.body.style.overflow = '';
  };

  gallery.querySelectorAll<HTMLButtonElement>('[data-photo]').forEach((btn) => {
    btn.addEventListener('click', () => show(Number(btn.dataset.photo)));
  });
  lightbox.querySelector('[data-lightbox-close]')?.addEventListener('click', close);
  lightbox.querySelector('[data-lightbox-prev]')?.addEventListener('click', () => show(index - 1));
  lightbox.querySelector('[data-lightbox-next]')?.addEventListener('click', () => show(index + 1));
  window.addEventListener('keydown', (e) => {
    if (lightbox.hidden) return;
    if (e.key === 'Escape') close();
    if (e.key === 'ArrowLeft') show(index - 1);
    if (e.key === 'ArrowRight') show(index + 1);
  });
}

// ---- forms: not wired to a backend yet ----
document.querySelectorAll<HTMLFormElement>('[data-inquiry]').forEach((form) => {
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    form.querySelector<HTMLElement>('.form-note')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  });
});
