/**
 * Client-side behaviors. Pages are static HTML generated by
 * scripts/build-content.mjs; this file only adds progressive enhancement:
 * sticky header, fullscreen menu, listing filters/sort, detail tabs, lightbox.
 */
import '@fontsource/jost/200.css';
import '@fontsource/jost/300.css';
import '@fontsource/barlow/400.css';
import '@fontsource/barlow/500.css';
import '@fontsource/barlow/600.css';
import '@fontsource/barlow/700.css';
import '@fontsource/cormorant/500-italic.css';
import './styles/main.css';

// ---- sticky header ----
function onScroll(): void {
  document.body.classList.toggle('is-scrolled', window.scrollY > 40);
}
window.addEventListener('scroll', onScroll, { passive: true });
onScroll();

// ---- fullscreen menu ----
const menu = document.querySelector<HTMLElement>('[data-menu]');
if (menu) {
  menu.hidden = true;
  document.querySelector('[data-menu-open]')?.addEventListener('click', () => (menu.hidden = false));
  menu.querySelector('[data-menu-close]')?.addEventListener('click', () => (menu.hidden = true));
  menu.querySelectorAll('a').forEach((a) => a.addEventListener('click', () => (menu.hidden = true)));
  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') menu.hidden = true;
  });
}

// ---- listings index: filter + sort ----
const grid = document.querySelector<HTMLElement>('[data-listing-grid]');
if (grid) {
  const hoodSelect = document.querySelector<HTMLSelectElement>('[data-filter-hood]');
  const sortSelect = document.querySelector<HTMLSelectElement>('[data-sort]');
  const emptyNote = document.querySelector<HTMLElement>('[data-empty-note]');
  const cards = Array.from(grid.querySelectorAll<HTMLElement>('.property-card'));

  const assetTabs = document.querySelector<HTMLElement>('[data-asset-tabs]');
  let assetFilter = '';

  const apply = (): void => {
    const hood = hoodSelect?.value ?? '';
    const sort = sortSelect?.value ?? 'recent';

    const sorted = [...cards].sort((a, b) => {
      const pa = Number(a.dataset.price);
      const pb = Number(b.dataset.price);
      if (sort === 'price-asc') return pa - pb;
      if (sort === 'price-desc') return pb - pa;
      return (b.dataset.date ?? '').localeCompare(a.dataset.date ?? '');
    });

    let visible = 0;
    for (const card of sorted) {
      const show =
        (!hood || card.dataset.hood === hood) &&
        (!assetFilter || card.dataset.asset === assetFilter);
      card.style.display = show ? '' : 'none';
      if (show) visible++;
      grid.appendChild(card);
    }
    if (emptyNote) emptyNote.hidden = visible > 0;
  };

  hoodSelect?.addEventListener('change', apply);
  sortSelect?.addEventListener('change', apply);

  assetTabs?.querySelectorAll<HTMLButtonElement>('button').forEach((btn) => {
    btn.addEventListener('click', () => {
      assetFilter = btn.dataset.asset ?? '';
      assetTabs.querySelectorAll('button').forEach((b) => b.classList.toggle('is-active', b === btn));
      apply();
    });
  });

  apply();
}

// ---- detail page: tabs ----
const tabs = document.querySelector<HTMLElement>('[data-tabs]');
if (tabs) {
  tabs.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach((btn) => {
    btn.addEventListener('click', () => {
      tabs.querySelectorAll('[data-tab]').forEach((b) => b.classList.toggle('is-active', b === btn));
      tabs
        .querySelectorAll<HTMLElement>('[data-panel]')
        .forEach((p) => p.classList.toggle('is-active', p.dataset.panel === btn.dataset.tab));
    });
  });
}

// ---- detail page: gallery lightbox ----
const gallery = document.querySelector<HTMLElement>('[data-gallery]');
const lightbox = document.querySelector<HTMLElement>('[data-lightbox]');
if (gallery && lightbox) {
  const photos = Array.from(gallery.querySelectorAll<HTMLTemplateElement>('[data-full-photo]')).map(
    (t) => t.content.textContent?.trim() ?? '',
  );
  const img = lightbox.querySelector<HTMLImageElement>('[data-lightbox-img]');
  const counter = lightbox.querySelector<HTMLElement>('[data-lightbox-counter]');
  let index = 0;

  const show = (i: number): void => {
    index = (i + photos.length) % photos.length;
    if (img) img.src = photos[index];
    if (counter) counter.textContent = `${index + 1} / ${photos.length}`;
    lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
  };
  const close = (): void => {
    lightbox.hidden = true;
    document.body.style.overflow = '';
  };

  gallery.querySelectorAll<HTMLButtonElement>('[data-photo]').forEach((btn) => {
    btn.addEventListener('click', () => show(Number(btn.dataset.photo)));
  });
  lightbox.querySelector('[data-lightbox-close]')?.addEventListener('click', close);
  lightbox.querySelector('[data-lightbox-prev]')?.addEventListener('click', () => show(index - 1));
  lightbox.querySelector('[data-lightbox-next]')?.addEventListener('click', () => show(index + 1));
  window.addEventListener('keydown', (e) => {
    if (lightbox.hidden) return;
    if (e.key === 'Escape') close();
    if (e.key === 'ArrowLeft') show(index - 1);
    if (e.key === 'ArrowRight') show(index + 1);
  });
}

// ---- maps ----
// Leaflet is only pulled in on pages that actually show a map, so listing
// index/detail pages stay light for everyone else.
const detailMap = document.querySelector<HTMLElement>('[data-map]');
const listingsMap = document.querySelector<HTMLElement>('[data-listings-map]');

if (detailMap || listingsMap) {
  void (async () => {
    const L = (await import('leaflet')).default;
    await import('leaflet/dist/leaflet.css');

    const TILES = 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png';
    // OSM (ODbL) and CARTO both require visible credit — kept, but styled
    // small and muted in CSS. The "Leaflet" prefix is library branding only
    // and is not required by its BSD licence, so it is switched off.
    const ATTRIB =
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>';

    const pin = (): L.DivIcon =>
      L.divIcon({
        className: 'map-pin',
        html: '<span></span>',
        iconSize: [18, 18],
        iconAnchor: [9, 9],
      });

    if (detailMap) {
      const lat = Number(detailMap.dataset.lat);
      const lng = Number(detailMap.dataset.lng);
      const map = L.map(detailMap, { scrollWheelZoom: false }).setView([lat, lng], 15);
      map.attributionControl.setPrefix('');
      L.tileLayer(TILES, { attribution: ATTRIB, maxZoom: 19 }).addTo(map);
      L.marker([lat, lng], { icon: pin(), title: detailMap.dataset.label }).addTo(map);
    }

    if (listingsMap) {
      // Clustering keeps the dense Montréal core readable when a couple of
      // Laurentians properties would otherwise force a region-wide zoom.
      await import('leaflet.markercluster');
      await import('leaflet.markercluster/dist/MarkerCluster.css');
      await import('leaflet.markercluster/dist/MarkerCluster.Default.css');

      const cards = Array.from(document.querySelectorAll<HTMLElement>('.property-card[data-lat]'));
      const map = L.map(listingsMap, { scrollWheelZoom: false }).setView([45.5019, -73.5674], 12);
      map.attributionControl.setPrefix('');
      L.tileLayer(TILES, { attribution: ATTRIB, maxZoom: 19 }).addTo(map);

      const cluster = L.markerClusterGroup({
        showCoverageOnHover: false,
        maxClusterRadius: 45,
        iconCreateFunction: (c) =>
          L.divIcon({
            className: 'map-cluster',
            html: `<span>${c.getChildCount()}</span>`,
            iconSize: [36, 36],
          }),
      });
      map.addLayer(cluster);

      const markers = cards.map((card) => {
        const m = L.marker([Number(card.dataset.lat), Number(card.dataset.lng)], { icon: pin() });
        const href = card.getAttribute('href') ?? '#';
        const thumb = card.dataset.thumb
          ? `<img src="${card.dataset.thumb}" alt="" loading="lazy" />`
          : '';
        m.bindPopup(
          `<a class="map-popup" href="${href}">${thumb}<strong>${card.dataset.sub ?? ''}</strong><span>${card.dataset.label ?? ''}</span></a>`,
        );
        return { card, marker: m };
      });

      // Keep pins in sync with the grid's filter state, and frame them.
      const refit = (): void => {
        const shown = markers.filter(({ card }) => card.style.display !== 'none');
        cluster.clearLayers();
        cluster.addLayers(shown.map(({ marker }) => marker));
        if (shown.length) {
          map.fitBounds(L.latLngBounds(shown.map(({ marker }) => marker.getLatLng())), {
            padding: [40, 40],
            maxZoom: 14,
          });
        }
      };
      refit();
      document.querySelectorAll('[data-filter-hood], [data-sort]').forEach((el) =>
        el.addEventListener('change', () => setTimeout(refit, 0)),
      );

      // Grid / map view toggle
      const grid = document.querySelector<HTMLElement>('[data-listing-grid]');
      document.querySelectorAll<HTMLButtonElement>('[data-view-toggle] button').forEach((btn) => {
        btn.addEventListener('click', () => {
          const wantMap = btn.dataset.view === 'map';
          document
            .querySelectorAll('[data-view-toggle] button')
            .forEach((b) => b.classList.toggle('is-active', b === btn));
          listingsMap.hidden = !wantMap;
          if (grid) grid.hidden = wantMap;
          if (wantMap) {
            map.invalidateSize();
            refit();
          }
        });
      });
    }
  })();
}

// ---- mortgage calculator ----
const calc = document.querySelector<HTMLElement>('[data-calc]');
if (calc) {
  const locale = document.documentElement.lang.startsWith('fr') ? 'fr-CA' : 'en-CA';
  const q = <T extends HTMLElement>(sel: string): T => calc.querySelector<T>(sel)!;

  const priceEl = q<HTMLInputElement>('[data-calc-price]');
  const downPctEl = q<HTMLInputElement>('[data-calc-down-pct]');
  const downAmtEl = q<HTMLInputElement>('[data-calc-down-amt]');
  const rateEl = q<HTMLInputElement>('[data-calc-rate]');
  const amortEl = q<HTMLSelectElement>('[data-calc-amort]');
  const freqEl = q<HTMLSelectElement>('[data-calc-freq]');
  const warnEl = q<HTMLElement>('[data-calc-warn]');

  const money = (n: number): string =>
    n.toLocaleString(locale, { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 });

  /** Canadian minimum down payment: 5% to $500k, 10% to $1.5M, 20% above. */
  const minDown = (price: number): number => {
    if (price > 1_500_000) return price * 0.2;
    if (price > 500_000) return 25_000 + (price - 500_000) * 0.1;
    return price * 0.05;
  };

  /**
   * Canadian mortgages compound semi-annually, not monthly — so the periodic
   * rate is derived from the semi-annual rate, not by dividing by 12.
   */
  const periodicRate = (annualPct: number, periodsPerYear: number): number =>
    Math.pow(1 + annualPct / 100 / 2, 2 / periodsPerYear) - 1;

  const payment = (principal: number, i: number, n: number): number =>
    i === 0 ? principal / n : (principal * i) / (1 - Math.pow(1 + i, -n));

  let syncing = false;
  const recalc = (from?: 'pct' | 'amt'): void => {
    if (syncing) return;
    syncing = true;

    const price = Math.max(0, Number(priceEl.value) || 0);
    if (from === 'amt') {
      const amt = Math.min(price, Math.max(0, Number(downAmtEl.value) || 0));
      downPctEl.value = price ? String(Math.round((amt / price) * 1000) / 10) : '0';
    } else {
      const pct = Math.min(100, Math.max(0, Number(downPctEl.value) || 0));
      downAmtEl.value = String(Math.round((price * pct) / 100));
    }

    const down = Math.min(price, Number(downAmtEl.value) || 0);
    const principal = Math.max(0, price - down);
    const years = Number(amortEl.value);
    const perYear = freqEl.value === 'biweekly' ? 26 : 12;
    const n = years * perYear;
    const i = periodicRate(Number(rateEl.value) || 0, perYear);
    const pay = principal > 0 ? payment(principal, i, n) : 0;

    q('[data-calc-payment]').textContent = money(pay);
    q('[data-calc-loan]').textContent = money(principal);
    q('[data-calc-interest]').textContent = money(Math.max(0, pay * n - principal));

    // Down payment below the legal minimum, or insurance unavailable
    const required = minDown(price);
    const warnings: string[] = [];
    if (price > 0 && down < required - 1) {
      warnings.push(`${calc.dataset.minDownLabel ?? ''} ${money(required)}`.trim());
    }
    if (price > 1_500_000 && down < price * 0.2 - 1) {
      warnings.push(calc.dataset.insuranceNote ?? '');
    }
    warnEl.textContent = warnings.filter(Boolean).join(' ');
    warnEl.hidden = warnings.length === 0;

    syncing = false;
  };

  priceEl.addEventListener('input', () => recalc('pct'));
  downPctEl.addEventListener('input', () => recalc('pct'));
  downAmtEl.addEventListener('input', () => recalc('amt'));
  [rateEl, amortEl, freqEl].forEach((el) => el.addEventListener('input', () => recalc()));
  recalc('pct');
}

// ---- forms: not wired to a backend yet ----
document.querySelectorAll<HTMLFormElement>('[data-inquiry]').forEach((form) => {
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    form.querySelector<HTMLElement>('.form-note')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  });
});
